/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReauthRouteImport } from './routes/reauth'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportNewRouteImport } from './routes/support.new'
import { Route as StatusUpdateRequiredRouteImport } from './routes/status.update-required'
import { Route as StatusSupplierOutageRouteImport } from './routes/status.supplier-outage'
import { Route as StatusProductUnavailableRouteImport } from './routes/status.product-unavailable'
import { Route as StatusPriceChangedRouteImport } from './routes/status.price-changed'
import { Route as StatusMaintenanceRouteImport } from './routes/status.maintenance'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRefundsRouteImport } from './routes/legal.refunds'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalAboutRouteImport } from './routes/legal.about'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as BrandsSlugRouteImport } from './routes/brands.$slug'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AccountSessionsRouteImport } from './routes/account.sessions'
import { Route as AccountSecurityRouteImport } from './routes/account.security'
import { Route as AccountRegionRouteImport } from './routes/account.region'
import { Route as AccountPromotionsRouteImport } from './routes/account.promotions'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountPhoneRouteImport } from './routes/account.phone'
import { Route as AccountPaymentRouteImport } from './routes/account.payment'
import { Route as AccountLanguageRouteImport } from './routes/account.language'
import { Route as AccountEmailRouteImport } from './routes/account.email'
import { Route as AccountDevicesRouteImport } from './routes/account.devices'
import { Route as AccountDeleteRouteImport } from './routes/account.delete'
import { Route as AccountAppearanceRouteImport } from './routes/account.appearance'
import { Route as ProductIdTopupRouteImport } from './routes/product.$id.topup'
import { Route as OrderIdSuccessRouteImport } from './routes/order.$id.success'
import { Route as OrderIdRefundRouteImport } from './routes/order.$id.refund'
import { Route as OrderIdPartialRouteImport } from './routes/order.$id.partial'
import { Route as OrderIdFulfillmentRouteImport } from './routes/order.$id.fulfillment'
import { Route as OrderIdFailedRouteImport } from './routes/order.$id.failed'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReauthRoute = ReauthRouteImport.update({
  id: '/reauth',
  path: '/reauth',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportNewRoute = SupportNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SupportRoute,
} as any)
const StatusUpdateRequiredRoute = StatusUpdateRequiredRouteImport.update({
  id: '/status/update-required',
  path: '/status/update-required',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusSupplierOutageRoute = StatusSupplierOutageRouteImport.update({
  id: '/status/supplier-outage',
  path: '/status/supplier-outage',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusProductUnavailableRoute =
  StatusProductUnavailableRouteImport.update({
    id: '/status/product-unavailable',
    path: '/status/product-unavailable',
    getParentRoute: () => rootRouteImport,
  } as any)
const StatusPriceChangedRoute = StatusPriceChangedRouteImport.update({
  id: '/status/price-changed',
  path: '/status/price-changed',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusMaintenanceRoute = StatusMaintenanceRouteImport.update({
  id: '/status/maintenance',
  path: '/status/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalRefundsRoute = LegalRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalAboutRoute = LegalAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LegalRoute,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriesRoute,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/brands/$slug',
  path: '/brands/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AccountSessionsRoute = AccountSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AccountRegionRoute = AccountRegionRouteImport.update({
  id: '/region',
  path: '/region',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPromotionsRoute = AccountPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPhoneRoute = AccountPhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPaymentRoute = AccountPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => AccountRoute,
} as any)
const AccountLanguageRoute = AccountLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => AccountRoute,
} as any)
const AccountEmailRoute = AccountEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AccountRoute,
} as any)
const AccountDevicesRoute = AccountDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AccountRoute,
} as any)
const AccountDeleteRoute = AccountDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAppearanceRoute = AccountAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AccountRoute,
} as any)
const ProductIdTopupRoute = ProductIdTopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => ProductIdRoute,
} as any)
const OrderIdSuccessRoute = OrderIdSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => OrderIdRoute,
} as any)
const OrderIdRefundRoute = OrderIdRefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => OrderIdRoute,
} as any)
const OrderIdPartialRoute = OrderIdPartialRouteImport.update({
  id: '/partial',
  path: '/partial',
  getParentRoute: () => OrderIdRoute,
} as any)
const OrderIdFulfillmentRoute = OrderIdFulfillmentRouteImport.update({
  id: '/fulfillment',
  path: '/fulfillment',
  getParentRoute: () => OrderIdRoute,
} as any)
const OrderIdFailedRoute = OrderIdFailedRouteImport.update({
  id: '/failed',
  path: '/failed',
  getParentRoute: () => OrderIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/legal': typeof LegalRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/reauth': typeof ReauthRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRouteWithChildren
  '/wallet': typeof WalletRoute
  '/account/appearance': typeof AccountAppearanceRoute
  '/account/delete': typeof AccountDeleteRoute
  '/account/devices': typeof AccountDevicesRoute
  '/account/email': typeof AccountEmailRoute
  '/account/language': typeof AccountLanguageRoute
  '/account/payment': typeof AccountPaymentRoute
  '/account/phone': typeof AccountPhoneRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/promotions': typeof AccountPromotionsRoute
  '/account/region': typeof AccountRegionRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/legal/about': typeof LegalAboutRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/order/$id': typeof OrderIdRouteWithChildren
  '/product/$id': typeof ProductIdRouteWithChildren
  '/status/maintenance': typeof StatusMaintenanceRoute
  '/status/price-changed': typeof StatusPriceChangedRoute
  '/status/product-unavailable': typeof StatusProductUnavailableRoute
  '/status/supplier-outage': typeof StatusSupplierOutageRoute
  '/status/update-required': typeof StatusUpdateRequiredRoute
  '/support/new': typeof SupportNewRoute
  '/order/$id/failed': typeof OrderIdFailedRoute
  '/order/$id/fulfillment': typeof OrderIdFulfillmentRoute
  '/order/$id/partial': typeof OrderIdPartialRoute
  '/order/$id/refund': typeof OrderIdRefundRoute
  '/order/$id/success': typeof OrderIdSuccessRoute
  '/product/$id/topup': typeof ProductIdTopupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/legal': typeof LegalRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/reauth': typeof ReauthRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRouteWithChildren
  '/wallet': typeof WalletRoute
  '/account/appearance': typeof AccountAppearanceRoute
  '/account/delete': typeof AccountDeleteRoute
  '/account/devices': typeof AccountDevicesRoute
  '/account/email': typeof AccountEmailRoute
  '/account/language': typeof AccountLanguageRoute
  '/account/payment': typeof AccountPaymentRoute
  '/account/phone': typeof AccountPhoneRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/promotions': typeof AccountPromotionsRoute
  '/account/region': typeof AccountRegionRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/legal/about': typeof LegalAboutRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/order/$id': typeof OrderIdRouteWithChildren
  '/product/$id': typeof ProductIdRouteWithChildren
  '/status/maintenance': typeof StatusMaintenanceRoute
  '/status/price-changed': typeof StatusPriceChangedRoute
  '/status/product-unavailable': typeof StatusProductUnavailableRoute
  '/status/supplier-outage': typeof StatusSupplierOutageRoute
  '/status/update-required': typeof StatusUpdateRequiredRoute
  '/support/new': typeof SupportNewRoute
  '/order/$id/failed': typeof OrderIdFailedRoute
  '/order/$id/fulfillment': typeof OrderIdFulfillmentRoute
  '/order/$id/partial': typeof OrderIdPartialRoute
  '/order/$id/refund': typeof OrderIdRefundRoute
  '/order/$id/success': typeof OrderIdSuccessRoute
  '/product/$id/topup': typeof ProductIdTopupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/legal': typeof LegalRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/reauth': typeof ReauthRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRouteWithChildren
  '/wallet': typeof WalletRoute
  '/account/appearance': typeof AccountAppearanceRoute
  '/account/delete': typeof AccountDeleteRoute
  '/account/devices': typeof AccountDevicesRoute
  '/account/email': typeof AccountEmailRoute
  '/account/language': typeof AccountLanguageRoute
  '/account/payment': typeof AccountPaymentRoute
  '/account/phone': typeof AccountPhoneRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/promotions': typeof AccountPromotionsRoute
  '/account/region': typeof AccountRegionRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/sessions': typeof AccountSessionsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/legal/about': typeof LegalAboutRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/order/$id': typeof OrderIdRouteWithChildren
  '/product/$id': typeof ProductIdRouteWithChildren
  '/status/maintenance': typeof StatusMaintenanceRoute
  '/status/price-changed': typeof StatusPriceChangedRoute
  '/status/product-unavailable': typeof StatusProductUnavailableRoute
  '/status/supplier-outage': typeof StatusSupplierOutageRoute
  '/status/update-required': typeof StatusUpdateRequiredRoute
  '/support/new': typeof SupportNewRoute
  '/order/$id/failed': typeof OrderIdFailedRoute
  '/order/$id/fulfillment': typeof OrderIdFulfillmentRoute
  '/order/$id/partial': typeof OrderIdPartialRoute
  '/order/$id/refund': typeof OrderIdRefundRoute
  '/order/$id/success': typeof OrderIdSuccessRoute
  '/product/$id/topup': typeof ProductIdTopupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/favorites'
    | '/home'
    | '/legal'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/reauth'
    | '/search'
    | '/support'
    | '/wallet'
    | '/account/appearance'
    | '/account/delete'
    | '/account/devices'
    | '/account/email'
    | '/account/language'
    | '/account/payment'
    | '/account/phone'
    | '/account/profile'
    | '/account/promotions'
    | '/account/region'
    | '/account/security'
    | '/account/sessions'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/reset'
    | '/auth/signup'
    | '/brands/$slug'
    | '/categories/$slug'
    | '/legal/about'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/order/$id'
    | '/product/$id'
    | '/status/maintenance'
    | '/status/price-changed'
    | '/status/product-unavailable'
    | '/status/supplier-outage'
    | '/status/update-required'
    | '/support/new'
    | '/order/$id/failed'
    | '/order/$id/fulfillment'
    | '/order/$id/partial'
    | '/order/$id/refund'
    | '/order/$id/success'
    | '/product/$id/topup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/favorites'
    | '/home'
    | '/legal'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/reauth'
    | '/search'
    | '/support'
    | '/wallet'
    | '/account/appearance'
    | '/account/delete'
    | '/account/devices'
    | '/account/email'
    | '/account/language'
    | '/account/payment'
    | '/account/phone'
    | '/account/profile'
    | '/account/promotions'
    | '/account/region'
    | '/account/security'
    | '/account/sessions'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/reset'
    | '/auth/signup'
    | '/brands/$slug'
    | '/categories/$slug'
    | '/legal/about'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/order/$id'
    | '/product/$id'
    | '/status/maintenance'
    | '/status/price-changed'
    | '/status/product-unavailable'
    | '/status/supplier-outage'
    | '/status/update-required'
    | '/support/new'
    | '/order/$id/failed'
    | '/order/$id/fulfillment'
    | '/order/$id/partial'
    | '/order/$id/refund'
    | '/order/$id/success'
    | '/product/$id/topup'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/favorites'
    | '/home'
    | '/legal'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/reauth'
    | '/search'
    | '/support'
    | '/wallet'
    | '/account/appearance'
    | '/account/delete'
    | '/account/devices'
    | '/account/email'
    | '/account/language'
    | '/account/payment'
    | '/account/phone'
    | '/account/profile'
    | '/account/promotions'
    | '/account/region'
    | '/account/security'
    | '/account/sessions'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/reset'
    | '/auth/signup'
    | '/brands/$slug'
    | '/categories/$slug'
    | '/legal/about'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/order/$id'
    | '/product/$id'
    | '/status/maintenance'
    | '/status/price-changed'
    | '/status/product-unavailable'
    | '/status/supplier-outage'
    | '/status/update-required'
    | '/support/new'
    | '/order/$id/failed'
    | '/order/$id/fulfillment'
    | '/order/$id/partial'
    | '/order/$id/refund'
    | '/order/$id/success'
    | '/product/$id/topup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  FavoritesRoute: typeof FavoritesRoute
  HomeRoute: typeof HomeRoute
  LegalRoute: typeof LegalRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRoute
  ReauthRoute: typeof ReauthRoute
  SearchRoute: typeof SearchRoute
  SupportRoute: typeof SupportRouteWithChildren
  WalletRoute: typeof WalletRoute
  BrandsSlugRoute: typeof BrandsSlugRoute
  OrderIdRoute: typeof OrderIdRouteWithChildren
  ProductIdRoute: typeof ProductIdRouteWithChildren
  StatusMaintenanceRoute: typeof StatusMaintenanceRoute
  StatusPriceChangedRoute: typeof StatusPriceChangedRoute
  StatusProductUnavailableRoute: typeof StatusProductUnavailableRoute
  StatusSupplierOutageRoute: typeof StatusSupplierOutageRoute
  StatusUpdateRequiredRoute: typeof StatusUpdateRequiredRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reauth': {
      id: '/reauth'
      path: '/reauth'
      fullPath: '/reauth'
      preLoaderRoute: typeof ReauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/new': {
      id: '/support/new'
      path: '/new'
      fullPath: '/support/new'
      preLoaderRoute: typeof SupportNewRouteImport
      parentRoute: typeof SupportRoute
    }
    '/status/update-required': {
      id: '/status/update-required'
      path: '/status/update-required'
      fullPath: '/status/update-required'
      preLoaderRoute: typeof StatusUpdateRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/supplier-outage': {
      id: '/status/supplier-outage'
      path: '/status/supplier-outage'
      fullPath: '/status/supplier-outage'
      preLoaderRoute: typeof StatusSupplierOutageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/product-unavailable': {
      id: '/status/product-unavailable'
      path: '/status/product-unavailable'
      fullPath: '/status/product-unavailable'
      preLoaderRoute: typeof StatusProductUnavailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/price-changed': {
      id: '/status/price-changed'
      path: '/status/price-changed'
      fullPath: '/status/price-changed'
      preLoaderRoute: typeof StatusPriceChangedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/maintenance': {
      id: '/status/maintenance'
      path: '/status/maintenance'
      fullPath: '/status/maintenance'
      preLoaderRoute: typeof StatusMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/refunds': {
      id: '/legal/refunds'
      path: '/refunds'
      fullPath: '/legal/refunds'
      preLoaderRoute: typeof LegalRefundsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/about': {
      id: '/legal/about'
      path: '/about'
      fullPath: '/legal/about'
      preLoaderRoute: typeof LegalAboutRouteImport
      parentRoute: typeof LegalRoute
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/brands/$slug': {
      id: '/brands/$slug'
      path: '/brands/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/account/sessions': {
      id: '/account/sessions'
      path: '/sessions'
      fullPath: '/account/sessions'
      preLoaderRoute: typeof AccountSessionsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/region': {
      id: '/account/region'
      path: '/region'
      fullPath: '/account/region'
      preLoaderRoute: typeof AccountRegionRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/promotions': {
      id: '/account/promotions'
      path: '/promotions'
      fullPath: '/account/promotions'
      preLoaderRoute: typeof AccountPromotionsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/phone': {
      id: '/account/phone'
      path: '/phone'
      fullPath: '/account/phone'
      preLoaderRoute: typeof AccountPhoneRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/payment': {
      id: '/account/payment'
      path: '/payment'
      fullPath: '/account/payment'
      preLoaderRoute: typeof AccountPaymentRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/language': {
      id: '/account/language'
      path: '/language'
      fullPath: '/account/language'
      preLoaderRoute: typeof AccountLanguageRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/email': {
      id: '/account/email'
      path: '/email'
      fullPath: '/account/email'
      preLoaderRoute: typeof AccountEmailRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/devices': {
      id: '/account/devices'
      path: '/devices'
      fullPath: '/account/devices'
      preLoaderRoute: typeof AccountDevicesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/delete': {
      id: '/account/delete'
      path: '/delete'
      fullPath: '/account/delete'
      preLoaderRoute: typeof AccountDeleteRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/appearance': {
      id: '/account/appearance'
      path: '/appearance'
      fullPath: '/account/appearance'
      preLoaderRoute: typeof AccountAppearanceRouteImport
      parentRoute: typeof AccountRoute
    }
    '/product/$id/topup': {
      id: '/product/$id/topup'
      path: '/topup'
      fullPath: '/product/$id/topup'
      preLoaderRoute: typeof ProductIdTopupRouteImport
      parentRoute: typeof ProductIdRoute
    }
    '/order/$id/success': {
      id: '/order/$id/success'
      path: '/success'
      fullPath: '/order/$id/success'
      preLoaderRoute: typeof OrderIdSuccessRouteImport
      parentRoute: typeof OrderIdRoute
    }
    '/order/$id/refund': {
      id: '/order/$id/refund'
      path: '/refund'
      fullPath: '/order/$id/refund'
      preLoaderRoute: typeof OrderIdRefundRouteImport
      parentRoute: typeof OrderIdRoute
    }
    '/order/$id/partial': {
      id: '/order/$id/partial'
      path: '/partial'
      fullPath: '/order/$id/partial'
      preLoaderRoute: typeof OrderIdPartialRouteImport
      parentRoute: typeof OrderIdRoute
    }
    '/order/$id/fulfillment': {
      id: '/order/$id/fulfillment'
      path: '/fulfillment'
      fullPath: '/order/$id/fulfillment'
      preLoaderRoute: typeof OrderIdFulfillmentRouteImport
      parentRoute: typeof OrderIdRoute
    }
    '/order/$id/failed': {
      id: '/order/$id/failed'
      path: '/failed'
      fullPath: '/order/$id/failed'
      preLoaderRoute: typeof OrderIdFailedRouteImport
      parentRoute: typeof OrderIdRoute
    }
  }
}

interface AccountRouteChildren {
  AccountAppearanceRoute: typeof AccountAppearanceRoute
  AccountDeleteRoute: typeof AccountDeleteRoute
  AccountDevicesRoute: typeof AccountDevicesRoute
  AccountEmailRoute: typeof AccountEmailRoute
  AccountLanguageRoute: typeof AccountLanguageRoute
  AccountPaymentRoute: typeof AccountPaymentRoute
  AccountPhoneRoute: typeof AccountPhoneRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountPromotionsRoute: typeof AccountPromotionsRoute
  AccountRegionRoute: typeof AccountRegionRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountSessionsRoute: typeof AccountSessionsRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAppearanceRoute: AccountAppearanceRoute,
  AccountDeleteRoute: AccountDeleteRoute,
  AccountDevicesRoute: AccountDevicesRoute,
  AccountEmailRoute: AccountEmailRoute,
  AccountLanguageRoute: AccountLanguageRoute,
  AccountPaymentRoute: AccountPaymentRoute,
  AccountPhoneRoute: AccountPhoneRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountPromotionsRoute: AccountPromotionsRoute,
  AccountRegionRoute: AccountRegionRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountSessionsRoute: AccountSessionsRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CategoriesRouteChildren {
  CategoriesSlugRoute: typeof CategoriesSlugRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesSlugRoute: CategoriesSlugRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface LegalRouteChildren {
  LegalAboutRoute: typeof LegalAboutRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundsRoute: typeof LegalRefundsRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalAboutRoute: LegalAboutRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundsRoute: LegalRefundsRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface SupportRouteChildren {
  SupportNewRoute: typeof SupportNewRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportNewRoute: SupportNewRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

interface OrderIdRouteChildren {
  OrderIdFailedRoute: typeof OrderIdFailedRoute
  OrderIdFulfillmentRoute: typeof OrderIdFulfillmentRoute
  OrderIdPartialRoute: typeof OrderIdPartialRoute
  OrderIdRefundRoute: typeof OrderIdRefundRoute
  OrderIdSuccessRoute: typeof OrderIdSuccessRoute
}

const OrderIdRouteChildren: OrderIdRouteChildren = {
  OrderIdFailedRoute: OrderIdFailedRoute,
  OrderIdFulfillmentRoute: OrderIdFulfillmentRoute,
  OrderIdPartialRoute: OrderIdPartialRoute,
  OrderIdRefundRoute: OrderIdRefundRoute,
  OrderIdSuccessRoute: OrderIdSuccessRoute,
}

const OrderIdRouteWithChildren =
  OrderIdRoute._addFileChildren(OrderIdRouteChildren)

interface ProductIdRouteChildren {
  ProductIdTopupRoute: typeof ProductIdTopupRoute
}

const ProductIdRouteChildren: ProductIdRouteChildren = {
  ProductIdTopupRoute: ProductIdTopupRoute,
}

const ProductIdRouteWithChildren = ProductIdRoute._addFileChildren(
  ProductIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  FavoritesRoute: FavoritesRoute,
  HomeRoute: HomeRoute,
  LegalRoute: LegalRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRoute,
  ReauthRoute: ReauthRoute,
  SearchRoute: SearchRoute,
  SupportRoute: SupportRouteWithChildren,
  WalletRoute: WalletRoute,
  BrandsSlugRoute: BrandsSlugRoute,
  OrderIdRoute: OrderIdRouteWithChildren,
  ProductIdRoute: ProductIdRouteWithChildren,
  StatusMaintenanceRoute: StatusMaintenanceRoute,
  StatusPriceChangedRoute: StatusPriceChangedRoute,
  StatusProductUnavailableRoute: StatusProductUnavailableRoute,
  StatusSupplierOutageRoute: StatusSupplierOutageRoute,
  StatusUpdateRequiredRoute: StatusUpdateRequiredRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
